### ISSUE TITLE
'numpy' has no attribute 'float128'

### ISSUE THREAD

**Issue by bennetthoogenboom** [DOI-USGS/geobipy#29]
For users running this code on windows, there are multiple calls to np.float128. This datatype is not available for windows machines. This results in continuous exceptions and constant rejection of models. 

Suggest changing to "np.longdouble". This will default to float128 on linux and float64 on windows, which is the best you can do. 

Changes should be made to "utilities" line 670 and "inference1D" line 382, though there may be other instances.

**Comment by leonfoks** [comment]
Cool thanks Bennett, Ill get that in!

**Comment by bennetthoogenboom** [comment]
Thanks. When I made these changes locally, I was finally able to get burn-in on Windows.
